### ISSUE TITLE
Use Docker build layers to speed up savant image builds

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#111]
For the savant image, see if you can do the first `pip install` in a separate layer, so that it only needs to be done once. Then compare the time to build versus your first local install. Here is some info:

https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds

**Comment by erikkaBaguio** [comment]
Docker images consist of their own building blocks called image layers. Image layers is defined by each line in the docker file. Each docker image consists of multiple layers that that are combined into the final image. Layering speeds up the build process because images are reusable that means anything that happened before will just be stored in a cache for later use.

Then for the multi-stage builds, it uses single docker file and does not require scripting to hold multiple docker files together.  In the docker file of a multi-stage builds, it allows multiple different base images and each of them begins a new stage of the build. It also allows to selectively copy artifacts from one stage to another, leaving behind everything you don’t want in the final image. So it saves space and also speeds up its run time.

**Comment by greenmoss** [comment]
I'm switching to a different approach, which will be faster than rebuilding the Docker image each time. See https://github.com/Doveps/mono/wiki/Developing-with-Docker.

This ticket is deprecated.
