### ISSUE TITLE
03-27-2018: Demo of current state of testing

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#132]
I'm posting this demo in advance while I search for solutions. @greenmoss  Please have a look if I got something wrong. Had an error along the way but somehow was bypassed.
Here's the link: https://youtu.be/cs4EezyxrkE

**Comment by greenmoss** [comment]
Notes from video:

https://youtu.be/cs4EezyxrkE?t=293 shows db still starting (see "health:starting"); you will need to wait for it to say "healthy" before you can connect to it. I note you did just that at https://youtu.be/cs4EezyxrkE?t=785.

Your docker downloads are extremely slow; many minutes to download. I'm wondering why they are downloading again; these should have been downloaded once and then cached locally.

To do development, you will need to switch to running savant from your local system, instead of within Docker. See the wiki "Developing with Docker" sections from "Set up virtualenv" down to "Develop".

I see what you mean by empty database. The first thing to check is the result of the first test: https://github.com/Doveps/mono/blob/master/savant/tests/test_basic.py#L21 The test succeeds with a "200", but does it actually insert anything? The first step would be to add logger statements in the code, and then run the test. For instance, entry point for the test is .../flavor/create (https://github.com/Doveps/mono/blob/master/savant/tests/test_basic.py#L14). That goes here: https://github.com/Doveps/mono/blob/master/savant/app/results.py#L10. Put in a `logger` statement there, to verify that the data you received is correct. Then keep following the data until it gets all the way to the database.

**Comment by greenmoss** [comment]
Many thanks for the video, this was really helpful for me to see where you are!

**Comment by JosiahRegencia** [comment]
Sure no problem. Will try the suggestion

**Comment by zerstoeren** [comment]
Diddo

**Comment by JosiahRegencia** [comment]
I realized that I wasn't familiar with loggers. 
Is this the one you mean? 
https://www.youtube.com/watch?v=-ARI4Cz-awo
