### ISSUE TITLE
04-10-2018 Report : Demo Explanation on test cases created

### ISSUE THREAD

**Issue by JosiahRegencia** [Doveps/mono#143]
Based on the comment from issue #140 

I made my changes comparing the base tables against the scan tables.

I explained my test cases in a demo I uploaded. [Click here for demo](https://youtu.be/QocC2ZcQnOw)

**Comment by greenmoss** [comment]
Good video, thanks! It looks like your approach is working, that is great!

I see what the test numbers are for now. For ordering, you would normally set up constructors/destructors for test cases. Normally the cases I have seen are that tests stand alone and do not depend on one another.

For the `count_` functions, do you have an API endpoint? These could be useful for end users as part of a `/get/count` type of URL. If you do that, you can also use those end points during yourt testing.

For the `Total` functions, are these totals, or more of a maximum? If the latter, I would call them `maximum`, otherwise I would assume they are going to add up all the values in the column.

Where is `data['Duplicates']` generated?
