### ISSUE TITLE
Test the database connection

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#28]
Include the database in testing, as part of #25.

**Comment by JosiahRegencia** [comment]
Does this mean I'll make unit tests for the Database also?

**Comment by greenmoss** [comment]
@josiah you only have to document what you did to enable the database testing. I saw you made some commits for it.

**Comment by JosiahRegencia** [comment]
Okay. So actually my commits about the Database testing were about trying to connect the database.
Initially I tried to make Travis connect to database Doveps. 
But I realized that Travis only reads one database name: travis_ci_test
That's why I changed database name in utils.py to travis_ci_test
engine = create_engine("postgresql://postgres:postgres@127.0.0.1:5432/travis_ci_test")

**Comment by greenmoss** [comment]
Sounds good; closing.
