### ISSUE TITLE
Upload a demo to the Doveps channel

### ISSUE THREAD

**Issue by greenmoss** [Doveps/mono#5]
Goal: record a demo from scanning a system up to using the api to display your first database entry

This is a follow-on to uploading your first demo video, and importing your first database entry. You should show your steps including all command line activity, database changes, and API output.

To close this ticket, you should include a link to the uploaded video.

**Comment by JosiahRegencia** [comment]
https://youtu.be/3zPXZd8QYHs

**Comment by zerstoeren** [comment]
Hi Josiah,

Where you mentioned having to use the default postgres user and password
because the Doveps users didn't work.  Did you run the Grant access to and
permissions script for Doveps to have add/change/delete privileges to the
databases?

I think it is heading in a positive direction.

Randy

On Aug 2, 2017 4:53 PM, "Josiah Eleazar T. Regencia" <
notifications@github.com> wrote:

https://youtu.be/3zPXZd8QYHs

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Doveps/mono/issues/5#issuecomment-319795055>, or mute
the thread

**Comment by JosiahRegencia** [comment]
Hi. Yes I did. For some reason it didn't work. But I'm gonna have to do it again. Might have to do some extra configurations

**Comment by greenmoss** [comment]
I re-closed, because you got this one done already :)

We can track new db work on a new ticket.
